// This file is autogenerated by the hyperdb compiler
/* eslint-disable camelcase */

const { IndexEncoder, c } = require('hyperdb/runtime')
const { version, getEncoding, setVersion } = require('./messages.js')

// '@registry/entry' collection key
const collection0_key = new IndexEncoder([
  IndexEncoder.STRING
], { prefix: 0 })

function collection0_indexify (record) {
  const a = record.name
  return a === undefined ? [] : [a]
}

// '@registry/entry' value encoding
const collection0_enc = getEncoding('@registry/entry/hyperdb#0')

// '@registry/entry' reconstruction function
function collection0_reconstruct (version, keyBuf, valueBuf) {
  const key = collection0_key.decode(keyBuf)
  setVersion(version)
  const record = c.decode(collection0_enc, valueBuf)
  record.name = key[0]
  return record
}
// '@registry/entry' key reconstruction function
function collection0_reconstruct_key (keyBuf) {
  const key = collection0_key.decode(keyBuf)
  return {
    name: key[0]
  }
}

// '@registry/entry'
const collection0 = {
  name: '@registry/entry',
  id: 0,
  encodeKey (record) {
    const key = [record.name]
    return collection0_key.encode(key)
  },
  encodeKeyRange ({ gt, lt, gte, lte } = {}) {
    return collection0_key.encodeRange({
      gt: gt ? collection0_indexify(gt) : null,
      lt: lt ? collection0_indexify(lt) : null,
      gte: gte ? collection0_indexify(gte) : null,
      lte: lte ? collection0_indexify(lte) : null
    })
  },
  encodeValue (version, record) {
    setVersion(version)
    return c.encode(collection0_enc, record)
  },
  trigger: null,
  reconstruct: collection0_reconstruct,
  reconstructKey: collection0_reconstruct_key,
  indexes: []
}

// '@registry/entry-by-drive-key' collection key
const index1_key = new IndexEncoder([
  IndexEncoder.BUFFER,
  IndexEncoder.STRING
], { prefix: 1 })

function index1_indexify (record) {
  const arr = []

  const a0 = record.driveKey
  if (a0 === undefined) return arr
  arr.push(a0)

  const a1 = record.name
  if (a1 === undefined) return arr
  arr.push(a1)

  return arr
}

// '@registry/entry-by-drive-key'
const index1 = {
  name: '@registry/entry-by-drive-key',
  id: 1,
  encodeKey (record) {
    return index1_key.encode(index1_indexify(record))
  },
  encodeKeyRange ({ gt, lt, gte, lte } = {}) {
    return index1_key.encodeRange({
      gt: gt ? index1_indexify(gt) : null,
      lt: lt ? index1_indexify(lt) : null,
      gte: gte ? index1_indexify(gte) : null,
      lte: lte ? index1_indexify(lte) : null
    })
  },
  encodeValue: (doc) => index1.collection.encodeKey(doc),
  encodeIndexKeys (record, context) {
    return [index1_key.encode([record.driveKey, record.name])]
  },
  reconstruct: (keyBuf, valueBuf) => valueBuf,
  offset: collection0.indexes.length,
  collection: collection0
}
collection0.indexes.push(index1)

// '@registry/entry-by-type' collection key
const index2_key = new IndexEncoder([
  IndexEncoder.STRING,
  IndexEncoder.STRING
], { prefix: 2 })

function index2_indexify (record) {
  const arr = []

  const a0 = record.type
  if (a0 === undefined) return arr
  arr.push(a0)

  const a1 = record.name
  if (a1 === undefined) return arr
  arr.push(a1)

  return arr
}

// '@registry/entry-by-type'
const index2 = {
  name: '@registry/entry-by-type',
  id: 2,
  encodeKey (record) {
    return index2_key.encode(index2_indexify(record))
  },
  encodeKeyRange ({ gt, lt, gte, lte } = {}) {
    return index2_key.encodeRange({
      gt: gt ? index2_indexify(gt) : null,
      lt: lt ? index2_indexify(lt) : null,
      gte: gte ? index2_indexify(gte) : null,
      lte: lte ? index2_indexify(lte) : null
    })
  },
  encodeValue: (doc) => index2.collection.encodeKey(doc),
  encodeIndexKeys (record, context) {
    return [index2_key.encode([record.type, record.name])]
  },
  reconstruct: (keyBuf, valueBuf) => valueBuf,
  offset: collection0.indexes.length,
  collection: collection0
}
collection0.indexes.push(index2)

// '@registry/entry-by-owner' collection key
const index3_key = new IndexEncoder([
  IndexEncoder.STRING,
  IndexEncoder.STRING
], { prefix: 3 })

function index3_indexify (record) {
  const arr = []

  const a0 = record.owner
  if (a0 === undefined) return arr
  arr.push(a0)

  const a1 = record.name
  if (a1 === undefined) return arr
  arr.push(a1)

  return arr
}

// '@registry/entry-by-owner'
const index3 = {
  name: '@registry/entry-by-owner',
  id: 3,
  encodeKey (record) {
    return index3_key.encode(index3_indexify(record))
  },
  encodeKeyRange ({ gt, lt, gte, lte } = {}) {
    return index3_key.encodeRange({
      gt: gt ? index3_indexify(gt) : null,
      lt: lt ? index3_indexify(lt) : null,
      gte: gte ? index3_indexify(gte) : null,
      lte: lte ? index3_indexify(lte) : null
    })
  },
  encodeValue: (doc) => index3.collection.encodeKey(doc),
  encodeIndexKeys (record, context) {
    return [index3_key.encode([record.owner, record.name])]
  },
  reconstruct: (keyBuf, valueBuf) => valueBuf,
  offset: collection0.indexes.length,
  collection: collection0
}
collection0.indexes.push(index3)

const collections = [
  collection0
]

const indexes = [
  index1,
  index2,
  index3
]

module.exports = { version, collections, indexes, resolveCollection, resolveIndex }

function resolveCollection (name) {
  switch (name) {
    case '@registry/entry': return collection0
    default: return null
  }
}

function resolveIndex (name) {
  switch (name) {
    case '@registry/entry-by-drive-key': return index1
    case '@registry/entry-by-type': return index2
    case '@registry/entry-by-owner': return index3
    default: return null
  }
}
