// This file is autogenerated by the hyperschema compiler
// Schema Version: 1
/* eslint-disable camelcase */
/* eslint-disable quotes */

const { c } = require('hyperschema/runtime')

const VERSION = 1

// eslint-disable-next-line no-unused-vars
let version = VERSION

// @registry/entry
const encoding0 = {
  preencode (state, m) {
    c.string.preencode(state, m.name)
    c.fixed32.preencode(state, m.driveKey)
    c.string.preencode(state, m.type)
    state.end++ // max flag is 2 so always one byte

    if (m.description) c.string.preencode(state, m.description)
    if (m.owner) c.string.preencode(state, m.owner)
  },
  encode (state, m) {
    const flags =
      (m.description ? 1 : 0) |
      (m.owner ? 2 : 0)

    c.string.encode(state, m.name)
    c.fixed32.encode(state, m.driveKey)
    c.string.encode(state, m.type)
    c.uint.encode(state, flags)

    if (m.description) c.string.encode(state, m.description)
    if (m.owner) c.string.encode(state, m.owner)
  },
  decode (state) {
    const r0 = c.string.decode(state)
    const r1 = c.fixed32.decode(state)
    const r2 = c.string.decode(state)
    const flags = c.uint.decode(state)

    return {
      name: r0,
      driveKey: r1,
      type: r2,
      description: (flags & 1) !== 0 ? c.string.decode(state) : null,
      owner: (flags & 2) !== 0 ? c.string.decode(state) : null
    }
  }
}

// @registry/entry/hyperdb#0
const encoding1 = {
  preencode (state, m) {
    c.fixed32.preencode(state, m.driveKey)
    c.string.preencode(state, m.type)
    state.end++ // max flag is 2 so always one byte

    if (m.description) c.string.preencode(state, m.description)
    if (m.owner) c.string.preencode(state, m.owner)
  },
  encode (state, m) {
    const flags =
      (m.description ? 1 : 0) |
      (m.owner ? 2 : 0)

    c.fixed32.encode(state, m.driveKey)
    c.string.encode(state, m.type)
    c.uint.encode(state, flags)

    if (m.description) c.string.encode(state, m.description)
    if (m.owner) c.string.encode(state, m.owner)
  },
  decode (state) {
    const r1 = c.fixed32.decode(state)
    const r2 = c.string.decode(state)
    const flags = c.uint.decode(state)

    return {
      name: null,
      driveKey: r1,
      type: r2,
      description: (flags & 1) !== 0 ? c.string.decode(state) : null,
      owner: (flags & 2) !== 0 ? c.string.decode(state) : null
    }
  }
}

function setVersion (v) {
  version = v
}

function encode (name, value, v = VERSION) {
  version = v
  return c.encode(getEncoding(name), value)
}

function decode (name, buffer, v = VERSION) {
  version = v
  return c.decode(getEncoding(name), buffer)
}

function getEnum (name) {
  switch (name) {
    default: throw new Error('Enum not found ' + name)
  }
}

function getEncoding (name) {
  switch (name) {
    case '@registry/entry': return encoding0
    case '@registry/entry/hyperdb#0': return encoding1
    default: throw new Error('Encoder not found ' + name)
  }
}

function getStruct (name, v = VERSION) {
  const enc = getEncoding(name)
  return {
    preencode (state, m) {
      version = v
      enc.preencode(state, m)
    },
    encode (state, m) {
      version = v
      enc.encode(state, m)
    },
    decode (state) {
      version = v
      return enc.decode(state)
    }
  }
}

const resolveStruct = getStruct // compat

module.exports = { resolveStruct, getStruct, getEnum, getEncoding, encode, decode, setVersion, version }
